config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :blogs
  resources :topics

  get 'home', to: 'pages#home'
  get 'about', to: 'pages#about'
  get 'resume', to: 'pages#resume'
  get "/:wedding" => "wedding#show"

  root to: 'pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged

  belongs_to :topics, optional: true

  paginates_per 5

  def self.most_recent
    order("updated_at DESC")
  end
end

app/models/concerns/title_concern.rb
module TitleConcern
  extend ActiveSupport::Concern

  def title_delimiter title
    " | " + title
  end
end

app/models/topic.rb
class Topic < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged

  has_many :blogs

  paginates_per 5

  def self.has_blogs
    includes(:blogs).where.not(blogs: { topic_id: nil })
  end
end

app/models/user.rb
class User < ApplicationRecord
  ############################################################################################
  ## PeterGate Roles                                                                        ##
  ## The :user role is added by default and shouldn't be included in this list.             ##
  ## The :root_admin can access any page regardless of access settings. Use with caution!   ##
  ## The multiple option can be set to true if you need users to have multiple roles.       ##
  petergate(roles: [:admin, :editor], multiple: false)                                      ##
  ############################################################################################ 
 

  devise :database_authenticatable, :rememberable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  include TitleConcern

  layout "blog"

  before_action :set_blog, only: [:show, :edit, :update, :destroy]
  before_action :set_topics_on_sidebar, except: [:update, :create, :destroy]
  before_action :set_title_on_header, except: [:update, :create, :destroy, :show]

  access all: [:show, :index], admin: :all

  # GET /blogs
  def index
    @blogs = Blog.most_recent.page(params[:page])
    @title = title_delimiter("Blog")
  end

  # GET /blogs/1
  def show
    @title = title_delimiter(@blog.title)
    @title_on_header = @blog.title
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
      else
        render :new
      end
    end
  end

  # PATCH/PUT /blogs/1
  def update
    if @blog.update(blog_params)
      redirect_to @blog, notice: 'Blog was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /blogs/1
  def destroy
    @blog.destroy
    redirect_to blogs_url, notice: 'Blog was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.friendly.find(params[:id])
    end

    def blog_params
      params.require(:blog).permit(:title, :body, :topic_id, :description)
    end

    def set_topics_on_sidebar
      @topics_on_sidebar = Topic.has_blogs
    end

    def set_title_on_header
      @title_on_header = "Blog"
    end
end

app/controllers/pages_controller.rb
require 'dotenv/load'

class PagesController < ApplicationController
  include TitleConcern

  before_action :set_prefix
  
  def home
    @title = "Lam Doan"
  end

  def about
    @title = @prefix + title_delimiter("About")
  end

  def resume
    @url = ENV.fetch("RESUME_URL")
    @title = @prefix + title_delimiter("Resume")
    @url_pdf = "https://docs.google.com/document/d/1ILyR5rVdyX4kQiIoWqIaKXEF-6LqEOAEujnGpY7gUcE/export?format=pdf"
    @url_publish = "https://docs.google.com/document/d/e/2PACX-1vQ3ZirMztSs8iPmhdjiDVJ2Q45H54neTHCzB6ECsgy5XoKmIk077viNp2M2vMTNY858zzdlGVmavH-i/pub?embedded=true"
  end

  private

  def set_prefix
    @prefix = "LVD"
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  include TitleConcern
  layout "blog"

  before_action :set_topic, only: [:show]
  before_action :set_topics_with_blogs, only: [:show]
  before_action :set_title_on_header, only: [:show]

  def show
    @blogs = @topic.blogs.most_recent.page(params[:page])
    @title = title_delimiter(@topic.title)
  end

  private

  def set_topic
    @topic = Topic.friendly.find(params[:id])
  end

  def set_topics_with_blogs
    @topics_on_sidebar = Topic.has_blogs
  end

  def set_title_on_header
    @title_on_header = @topic.title
  end
end

app/controllers/wedding_controller.rb
class WeddingController < ApplicationController
  layout 'wedding'
  
  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
  class CodeRayify < Redcarpet::Render::HTML
    def block_code code, language
      CodeRay.scan(code, language).div
    end
  end

  def markdown text
    if !text.nil?
      coderayified = CodeRayify.new(with_toc_data: true, hard_wrap: true)

      settings = {
        fenced_code_blocks: true,
        no_intra_emphasis: true,
        autolink: true,
        superscript: true,
        strikethrough: true,
      }

      markdown = Redcarpet::Markdown.new(coderayified, settings)
      markdown.render(text).html_safe
    end
  end

  def standard_date_format date
    if !date.nil?
      date.strftime("%B %d, %Y")
    end
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/wedding_helper.rb
module WeddingHelper
end

app/views/blogs/_blog.html.erb
<%= link_to blog.title, blog, class: "blog-title" %>

<p class="blog-description">
  Last updated: <%= standard_date_format(blog.updated_at) %>
</p>

<div>
  <% if user_signed_in? %>
    <%= link_to 'Edit', edit_blog_path(blog) %> | 
    <%= link_to 'Delete', blog, method: :delete, data: { confirm: 'Are you sure?' } %>
  <% end %>
</div>

<p class="blog-description">
  <%= markdown(blog.description) %>
</p>

app/views/blogs/_form.html.erb
<%= form_with(model: blog, local: true) do |form| %>
  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.submit "Update", class: "btn btn-primary" %>
  </div>

  <div class="form-group">
    <%= form.text_field :title, class: "form-control", placeholder: "Title" %>
  </div>

  <div class="form-group">
    <%= form.collection_select(:topic_id, Topic.all, :id, :title, class: "form-control") %>
  </div>

  <div class="form-group">
    <%= form.text_area :description, rows: 5, class: "form-control", placeholder: "Brief description" %>
  </div>

  <div class="form-group"  id="my_anchor">
    <%= form.text_area :body, rows: 29, class: "form-control", placeholder: "Body" %>
  </div>

  <div class="form-group">
    <%= form.submit "Update", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<%= link_to 'Show', @blog %> | <%= link_to 'Delete', @blog, method: :delete, data: { confirm: 'Are you sure?' } %> | <%= link_to 'Back to Blog', blogs_path %>

<h1>Editing Blog</h1>

<%= render 'form', blog: @blog %>

app/views/blogs/index.html.erb
<nav class="blog-pagination">
  <%= paginate @blogs %>
</nav>

<%= render @blogs %>

<nav class="blog-pagination">
  <%= paginate @blogs %>
</nav>

app/views/blogs/new.html.erb
<h1>New Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<% if user_signed_in? %>
  <%= link_to 'Edit', edit_blog_path(@blog, anchor: "my_anchor") %> |
<% end %>
<%= link_to 'Back to Blog', blogs_path %>


<p class="blog-body">
  <%= markdown(@blog.body) %>
</p>

<div class="blog-bottom-links">
  <%= link_to "Back to Top", "#" %> | <%= link_to 'Back to Blog', blogs_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
    
    <title><%= @title %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= render "shared/google_analytics" %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= favicon_link_tag asset_path("favicon.ico") %>
  </head>

  <body>
    <div class="cover-container d-flex h-100 p-3 mx-auto flex-column">
      <%= render "shared/nav_bar" %>

      <% if notice || alert %>
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
      <% end %>

      <%= yield %>
      
      <%= render "shared/footer" %>
    </div>
  </body>
</html>

app/views/layouts/blog.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
    
    <title>LVD<%= @title %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'blogs', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= render "shared/google_analytics" %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= favicon_link_tag asset_path("favicon.ico") %>
  </head>

  <body>
    <%= render "shared/blog_nav_bar" %>
    
    <div class="container">
      <%= render "shared/blog_header" %>

      <main role="main">
        <div class="row">
          <aside class="col-md-3 blog-sidebar">
            <%= render "shared/blog_sidebar" %>
          </aside>

          <div class="col-md-9 main">
            <%= yield %>
          </div>


        </div>
      </main>
    </div>

    <%= render "shared/blog_footer" %>
  </body>
</html>

app/views/layouts/wedding.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
    
    <title>Wedding</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'wedding', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= render "shared/google_analytics" %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag asset_path("ring.png") %>
  </head>

  <div class="container">
        <%= yield %>

        <iframe src="https://lamvdoan.s3.us-east-2.amazonaws.com/wedding/Ed+Sheeran+-+Perfect.mp3" allow="autoplay" height="0" width="0"></iframe>    
  </div>
</html>

app/views/pages/about.html.erb
<main role="main" class="inner cover">
  <div class="row">
    <div class="col-md-8">

      <div class="row content-section">
        <div class="col-md-5 center">
          <%= image_tag "LamDoan.jpg", width: 300, class: "about-image-mobile" %>
        </div>
        <div class="col-md-7">
          <h2>It started with a spark</h2>
          <div class="paragraph">
            My engineering career began as a QA.  I learned how to interact with different roles, the entire software lifecycle, and of course, testing.  My career kicked started when I completed the accelerated Java class created by the engineering leadership.  After completing the course, I started coding automated tests for front-end and back-end applications.  I am also part of a <a href="https://patents.justia.com/assignee/grubhub-inc">patent</a> during my tenure at Grubhub.
          </div>
        </div>
      </div>

      <div class="row content-section">
        <div class="col-md-7">
          <h2>Rolling into the deep</h2>
          <div class="paragraph">
            I decided to join Outcome Health on September 2016.  I became more curious with coding, and this grew into building a test framework from scratch, working with data analytics, and learning how to build an Android app my side project.  My last project there was the most complex piece of software I have ever built, the <a href=<%= blog_path(4) %>>Analytics Validation Service</a>.  
          </div>
        </div>
        <div class="col-md-4 center">
          <%= image_tag "LamOutcome.jpg", width: 300 %>
        </div>
      </div>

      <div class="row content-section">
        <div class="col-md-5 center">
          <%= image_tag "LamTemple.jpg", width: 300, class: "about-image-mobile" %>
        </div>
        <div class="col-md-7">
          <h2>Doing what I love</h2>
          <div class="paragraph">
            The more I learned over time, the more obsessed I became.  On November 2018, I quit my job to study application development and code full time.  My first project included Javascript, React, and HTML/CSS.  After that, I moved on to Ruby/Rails and worked on this profile website.  The most valuable lesson I've acquired as an engineer is that curiosity and learning never stops.
          </div>
        </div>
      </div>
    </div>

    <div class="col-md-1"></div>
    <%= render "shared/about_sidebar" %>
  </div>
</main>

app/views/pages/home.html.erb
<%= render "shared/video_play" %>

<main role="main" class="inner cover text-center">
  <h1 class="cover-heading">Hi, I'm Lam.</h1>
  <p class="lead home-summary">
    I am a <b>Software Engineer</b> 🤠 at Fetch. I have a degree in Computer Engineering (UIC) and a decade of QA/Automation experience.

    <br><br>

    My interests include board games, karaoke, technology, house projects, biking, basketball, running, weight lifting, health/nutrition. I enjoy exploring the world and meeting people.  

    <br><br>

    I am blessed with my wife Jacki 👱🏽‍♀️ and our dog Dolce 🦊.
  </p>
</main>

app/views/pages/resume.html.erb
<main role="main" class="inner cover">
  <div class=resume>
    <div class="btn download-resume-button">
      <%= link_to "Download Resume", @url_pdf %>
    </div>

    <iframe src="<%= @url_publish %>" height="100%" width="100%" style="background: #FFFFFF;"></iframe>
  </div>
</main>

app/views/shared/_about_sidebar.html.erb
<div class="col-md-3">
  <div class="dark-container">
    <div class="sidebar-section">
      <h3>Contact</h3>
      <div class="hl"></div>
      
      <h5 class="heading">Home</h5>
      <p>Chicago, IL</p>
      
      <h5 class="heading">Email</h5>
      <p>Lamvdoan@gmail.com</p>
    </div>

    <div class="sidebar-section">
      <h3>Social Media</h3>
      <div class="hl"></div>

      <ul class="list-unstyled social-links">
        <li><a href="https://github.com/lamvdoan/"><%= fa_icon "github-square" %></a></li>
        <li><a href="https://www.linkedin.com/in/lamdoan/"><%= fa_icon "linkedin" %></a></li>
        <li><a href="https://www.facebook.com/van.doan.10"><%= fa_icon "facebook-square" %></a></li>
        <li><a href="https://twitter.com/lamvdoan"><%= fa_icon "twitter-square" %></a></li>
        <li><a href="https://www.tripadvisor.com/Profile/lamvdoan"><%= fa_icon "tripadvisor" %></a></li>
        <li><a href="https://tinyurl.com/gr5tg28"><%= fa_icon "gamepad" %></a></li>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_blog_footer.html.erb
<footer class="blog-footer">
  <%= render "shared/footer" %>
</footer>

app/views/shared/_blog_header.html.erb
<header class="blog-header py-3">
  <div class="align-items-center">
    <p class="blog-header-title"><%= @title_on_header %></p>
  </div>

  <% if user_signed_in? %>
    <%= link_to 'New Blog', new_blog_path %>
  <% end %>
</header>

app/views/shared/_blog_nav_bar.html.erb
<header class="nav-attribute">
  <div class="masthead-brand">
    <%= link_to 'Lam Doan', root_path, class: "nav-link" %>
  </div>

  <nav class="nav justify-content-center">
    <%= render "shared/nav_links" %>
  </nav>
</header>

app/views/shared/_blog_sidebar.html.erb
<div class="p-4-custom">
  <h4>Topics</h4>
  <% unless @topics_on_sidebar.blank? %>
    <% @topics_on_sidebar.each do |topic| %>
      <%= link_to topic.title, topic_path(topic), class: "nav-link" %>
    <% end %>
  <% end %>
</div>

app/views/shared/_footer.html.erb
<footer class="mastfoot mt-auto">
  <div style="margin: .5rem;">
    <span class="footer-quote">"I have no special talent, I am only passionately curious."</span>
    <span class="footer-author">– Albert Einstein</span>
  </div>
</footer>

app/views/shared/_google_analytics.html.erb
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-145386653-1"></script>
  <script>
    var environment = <%= Rails.env.production? %>;
    
    if (environment == false) {
      console.log("_google_analytics.html.erb: DEV environment");
    } else if (environment == true) {
      console.log("_google_analytics.html.erb: PROD environment");
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());
      gtag('config', '<%= ENV.fetch("GOOGLE_TRACKING_ID") %>');
    } else {
      console.log("_google_analytics.html.erb: UNKNOWN environment");
    }
  </script>

app/views/shared/_google_analytics_html.erb
<% if Rails.env.production? %>
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-145386653-1"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', <%= ENV.fetch("GOOGLE_TRACKING_ID") %>);
  </script>
<% end %>

app/views/shared/_nav_bar.html.erb
<header class="masthead mb-auto">
  <div class="inner">
    <h3 class="masthead-brand">Lam Doan</h3>
  </div>

  <nav class="nav nav-masthead justify-content-center">
    <%= render "shared/nav_links" %>
  </nav>
</header>

app/views/shared/_nav_links.html.erb
<%= link_to 'Home', root_path, class: "nav-link" %>
<%= link_to 'About', about_path, class: "nav-link" %>
<%= link_to 'Resume', resume_path, class: "nav-link" %>
<%= link_to 'Blog', blogs_path, class: "nav-link" %>

<% if user_signed_in? %>
  <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: "nav-link" %>
<% else %>
  <%= link_to 'Admin', new_user_session_path, class: "nav-link" %>
<% end %>

app/views/shared/_video_play.html.erb
<%= video_tag(
  "cool.mp4",
  id: "background-video",
  autoplay: true,
  loop: true,
  muted: true,
  playsinline: true
) %>

app/views/topics/_topic.html.erb
<%= link_to topic.title, topic_path(topic) %>

app/views/topics/show.html.erb
<nav class="blog-pagination">
  <%= paginate @blogs %>
</nav>

<%= render @blogs %>

<nav class="blog-pagination">
  <%= paginate @blogs %>
</nav>

app/views/wedding/show.html.erb
<div class="central">

<div class="info-box">
    <p class="name">Janki & Lam</p>
  </div>
  
  <div class="image">
    <img src="https://lamvdoan.s3.us-east-2.amazonaws.com/wedding/engagement.png" width="755" height="527">
  </div>

  <div class="info-box">
  </div>

  <div class="info-box">
    <p class="title">Wedding Ceremony</p>
    <p class="text">Due to the latest quarantine restriction, the wedding ceremony is cancelled.  </p>
  </div>
  
  <div class="info-box">
    <p class="title">Gifts</p>
    <p class="quote">No gifts necessary.  Your blessings are much appreciated.</p>
  </div>

</div>

app/views/wedding/show_bak.html.erb
<div class="central">

<div class="info-box">
    <p class="name">Janki & Lam</p>
    <p class="text italic">November 27, 2020</p>
  </div>
  
  <div class="image">
    <img src="https://lamvdoan.s3.us-east-2.amazonaws.com/wedding/engagement.png" width="755" height="527">
  </div>

  <div class="info-box">
  </div>

  <div class="info-box">
    <p class="title">Wedding Ceremony</p>
    <p class="text">Janki's Parents' House, Naperville, IL</p>
    <p class="text">Friday, November 27, 2020<br>3:00 PM CDT</p>
    <p class="text">Zoom Link to Live Wedding Ceremony (available on day of)<br>
      <a href="https://google.com">Watch us get married!</a>
    </p>
  </div>
  
  <div class="info-box">
    <p class="title">Gifts</p>
    <p class="quote">No gifts necessary.  Your blessings are much appreciated.</p>
  </div>

</div>